/**
 * Temporary static rows for UI review when list-web returns no data.
 * Remove once real expense records are available in the environment.
 */
import { ExpenseListItem } from "./types";

export const MOCK_EXPENSES: ExpenseListItem[] = [
  {
    id: 9001,
    date: "29 Jul 2026 10:15",
    submittedBy: {
      name: "Taras Pukish",
      role: "Driver",
      initials: "TP",
      avatarColor: "#7C3AED",
    },
    project: "Hackney Flat 67",
    category: "General",
    description: "Front tyres replacement",
    amount: 384.0,
    currency: "£",
    status: "approved",
    attachmentCount: 1,
  },
  {
    id: 9002,
    date: "28 Jul 2026 16:42",
    submittedBy: {
      name: "Dmytro Vovk",
      role: "Site Manager",
      initials: "DV",
      avatarColor: "#2563EB",
    },
    project: "Islington Block C",
    category: "Materials",
    description: "Paint and primers",
    amount: 62.5,
    currency: "£",
    status: "pending",
    attachmentCount: 1,
  },
  {
    id: 9003,
    date: "28 Jul 2026 11:08",
    submittedBy: {
      name: "Igor Torchynovych",
      role: "Foreman",
      initials: "IT",
      avatarColor: "#0D9488",
    },
    project: "Haringey Disrepair",
    category: "Tools",
    description: "Drill bit set",
    amount: 48.0,
    currency: "£",
    status: "pending",
    attachmentCount: 2,
  },
  {
    id: 9004,
    date: "27 Jul 2026 09:30",
    submittedBy: {
      name: "Anna Kovalenko",
      role: "Admin",
      initials: "AK",
      avatarColor: "#DB2777",
    },
    project: "Camden Refurb",
    category: "Travel",
    description: "Site visit mileage",
    amount: 36.0,
    currency: "£",
    status: "approved",
    attachmentCount: 1,
  },
  {
    id: 9005,
    date: "26 Jul 2026 14:55",
    submittedBy: {
      name: "Oleh Melnyk",
      role: "Electrician",
      initials: "OM",
      avatarColor: "#EA580C",
    },
    project: "Hackney Flat 12",
    category: "Materials",
    description: "Cable and connectors",
    amount: 112.75,
    currency: "£",
    status: "sent",
    attachmentCount: 1,
  },
  {
    id: 9006,
    date: "25 Jul 2026 08:20",
    submittedBy: {
      name: "Sofia Bondar",
      role: "RLO",
      initials: "SB",
      avatarColor: "#4F46E5",
    },
    project: "Tottenham Works",
    category: "General",
    description: "Safety equipment",
    amount: 89.99,
    currency: "£",
    status: "approved",
    attachmentCount: 0,
  },
  {
    id: 9007,
    date: "24 Jul 2026 17:10",
    submittedBy: {
      name: "Maksym Shevchenko",
      role: "Plumber",
      initials: "MS",
      avatarColor: "#0891B2",
    },
    project: "Enfield Unit 4",
    category: "Materials",
    description: "Pipe fittings",
    amount: 49.5,
    currency: "£",
    status: "pending",
    attachmentCount: 1,
  },
  {
    id: 9008,
    date: "23 Jul 2026 13:05",
    submittedBy: {
      name: "Yulia Petrenko",
      role: "Driver",
      initials: "YP",
      avatarColor: "#9333EA",
    },
    project: "Walthamstow House",
    category: "Fuel",
    description: "Van diesel refill",
    amount: 75.0,
    currency: "£",
    status: "sent",
    attachmentCount: 1,
  },
];
